[package]
name = "secure-messaging"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
rand = "0.8.5"
rsa = { version = "0.9.7", features = ["sha2"] }
tokio = { version = "1.43.0", features = ["full"] }
tokio-macros = "2.5.0"
